### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by anselb** [ryanlsmith4/tweet-generator#1]
- Your dictionary words functions work, but you may consider doing a bit of refactoring to change the output of the function.
- You may consider adding spacing to each histogram function to split things up such as variable declaration, return statements, or the two cases that a word is in the histogram or not. 
- If you borrow code or get a lot of help from someone's code, be sure to credit that person near the borrowed code in a comment.
- Your histogram functions appear to be simple and are relatively easy to read without comments or spacing.

**Comment by ryanlsmith4** [comment]
Thanks
